<?php

/**
 * @file
 * Used to integrate the SuperSaaS appointment scheduling.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function supersaas_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.supersaas':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t("This module displays a 'Book now' button that automatically logs the user into a SuperSaaS schedule using his Drupal user name. It passes the user's information along, creating or updating the user's information on SuperSaaS as needed. This saves users from having to log in twice.") . '</p>';
      $output .= '<p>' . t('For more details visit: <a href=":supersaas_spec">SuperSaaS Support', array(':supersaas_spec' => 'http://www.supersaas.com/info/doc/integration/drupal_integration')) . '</p>';
      return $output;
  }
}
